name: eva
description: A menstrual health companion app.
publish_to: 'none' # Remove this line if you intend to publish the package.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Compatible with Flutter 3.x as of March 2025

dependencies:
  flutter:
    sdk: flutter

  # UI and Animation
  flutter_animate: ^4.5.0 # For animations in startup_screen.dart
  table_calendar: ^3.0.9 # For calendar in home_screen.dart

  # Optional: Local Storage (if you want to persist data locally)
  shared_preferences: ^2.2.3 # Uncomment if you implement local storage for profiles or logs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2 # For linting and code quality

flutter:
  uses-material-design: true

  # Assets (uncomment and adjust if you have assets like profile_placeholder.png)

  # Fonts (optional, uncomment and configure if needed)
  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf